version: "3.7"

services:
  panela-backend:
    environment: 
      - PORT=${PORT}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - URI_MONGODB=${URI_MONGODB}
      - SESSION_SECRET=${SESSION_SECRET}
      - AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}
      - MONGO_PSWD=${MONGO_PSWD}
      - AUDIENCE=${AUDIENCE}
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: panela-server
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: npm run dev
  mongodb:
    image: mongo:latest
    container_name: panela-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
