version: "3.7"

services:
  panela-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: panela-server
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: npm run dev
    environment:
      - URI_MONGODB=mongodb://mongodb:27017/yourDatabase
  mongodb:
    image: mongo:latest
    container_name: panela-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
